= Development Box
:toc:
:numbered:

:archlinux-version:  2020.03.04
:ubuntu-version: 20190914.0.0
:uri-archlinux-version: https://app.vagrantup.com/archlinux/boxes/archlinux/versions/{archlinux-version}
:uri-ubuntu-version: https://app.vagrantup.com/ubuntu/boxes/bionic64/versions/{ubuntu-version}
:uri-macos-virtualbox-install-instructions: https://github.com/paulojeronimo/dicas-osx/blob/master/homebrew.md#virtualbox
:uri-macos-vagrant-install-instructions: https://github.com/paulojeronimo/dicas-osx/blob/master/homebrew.md#vagrant
:sensitive-tar: tmp/sensitive.tar
:backup-tar: tmp/backup.tar

This project offers you scripts to provision a
development box using one of the following
operational systems:

. Arch Linux (version {uri-archlinux-version}[
{archlinux-version}^]).
. Ubuntu (bionic64 version {uri-ubuntu-version}[
{ubuntu-version}^]).

== Prerequisites

. Install VirtualBox
  ({uri-macos-virtualbox-install-instructions}[macOS
instructions^]).
. Install Vagrant
  ({uri-macos-vagrant-install-instructions}[macOS
instructions^]).

== Procedures

To start de VM use the link:scripts/up[] script:

----
$ ./scripts/up
----

NOTE: Using the parameter `-f` this script will
force the generation of the `{sensitive-tar}`
file.

To destroy de VM use the link:scripts/destroy[] script:

----
$ ./scripts/destroy
----

NOTE: Using the parameter `-f` this script will
destroy the VM without asking you about the
`{backup-tar}` file.

== Configuration (optional steps)

The file link:config-default.yaml[] (currently
pointing to link:config/archlinux.yaml[])
configures the default values used by the
provisioning process.

You may want to use another Vagrant Box or
configure your own settings by copying one file
from link:config[] dir to `config.yaml`
and editing this new one, like in the following
commands:

----
$ cp config/ubuntu-bionic64.yaml config.yaml
$ vim config.yaml
----

Currently, to do this, you can use the following
files:

. link:config/archlinux.yaml[]
. link:config/ubuntu-bionic64.yaml[]

There are some other points that you can
configure.
All script files with the '.sample' extension can
be switched by files with the same name but
without this extension.

----
$ find . -type f -name '*.sample' ! -path './.git/*'
./provision/Ubuntu/install.sample
./provision/common/install.sample
./provision/common/config.sample
./provision/Arch/install.sample
./scripts/create-sensitive-tar.sample
./scripts/create-backup-tar.sample
----

So, if you create a file
`./scripts/create-sensitive-tar` it will be used
in place of the file
`./scripts/create-sensitive-tar.sample`.
