= Development Box
:toc:
:icons: font
:numbered:

:archlinux-version:  2020.03.04
:ubuntu-version: 20200407.0.0

:uri-archlinux-version: https://app.vagrantup.com/archlinux/boxes/archlinux/versions/{archlinux-version}
:uri-ubuntu-version: https://app.vagrantup.com/ubuntu/boxes/bionic64/versions/{ubuntu-version}
:uri-macos-virtualbox-install-instructions: https://github.com/paulojeronimo/dicas-osx/blob/master/homebrew.md#virtualbox
:uri-macos-vagrant-install-instructions: https://github.com/paulojeronimo/dicas-osx/blob/master/homebrew.md#vagrant

:archlinux: https://archlinux.org[Arch Linux^]
:ubuntu: https://ubuntu.org[Ubuntu^]
:macOS: https://www.apple.com/macos/catalina/[macOS^]
:Cygwin: https://www.cygwin.com/[Cygwin^]
:MSYS: http://www.mingw.org/wiki/MSYS[MSYS^]
:VirtualBox: https://virtualbox.org[VirtualBox^]
:Vagrant: https://www.vagrantup.com/[Vagrant^]

:sensitive-tar: tmp/sensitive.tar
:backup-tar: tmp/backup.tar

This project offers you scripts to provision a
development box using one of the following
operating system (OS):

. Arch Linux (version {uri-archlinux-version}[
{archlinux-version}^]).
. Ubuntu (bionic64 version {uri-ubuntu-version}[
{ubuntu-version}^]).

You have some alternatives to use the scripts
provided by this repo:

. You can use it directly into your OS if you are
using one of the above.
. If you prefer not to use {Vagrant}, you can
create a Virtual Machine (VM) by yourself and
install one of the OS listed above.
. You can use {VirtualBox} and {Vagrant} if you
are running a {macOS} or any other OS that
supports the execution of Bash scripts
(including a Windows environment running {Cygwin}
or {MSYS}. [red]#I did not test such thing yet!#).

The following instructions need to be
followed if you are in the last of the
alternatives above.

== Prerequisites

. Install VirtualBox
  ({uri-macos-virtualbox-install-instructions}[macOS
instructions^]).
. Install Vagrant
  ({uri-macos-vagrant-install-instructions}[macOS
instructions^]).

== Procedures

To start de VM use the link:scripts/up[] script:

----
$ ./scripts/up
----

NOTE: Using the parameter `-f` this script will
force the generation of the `{sensitive-tar}`
file.

To destroy de VM use the link:scripts/destroy[]
script:

----
$ ./scripts/destroy
----

NOTE: Using the parameter `-f` this script will
destroy the VM without asking you about the
`{backup-tar}` file.

== Configuration (optional steps)

The file link:config-default.yaml[] (currently
pointing to link:config/archlinux.yaml[])
configures the default values used by the
provisioning process.

You may want to use another Vagrant Box or
configure your own settings by copying one file
from link:config[] dir to `config.yaml`
and editing this new one, like in the following
commands:

----
$ cp config/ubuntu-bionic64.yaml config.yaml
$ vim config.yaml
----

[NOTE]
====
If you just want to use another configuration
alternative (without modifying it), you can link
simple link `config.yaml` to it:

----
$ ln -sf config/ubuntu-bionic64.yaml config.yaml
----
====

To do this, you can use one of the following
files (but there are others):

. link:config/archlinux.yaml[]
. link:config/archlinux-local-mirror.yaml[] (same
  as above but configured to use a local mirror).
. link:config/ubuntu-bionic64.yaml[]

There are some other points that you can
configure.
All script files with the '.sample' extension can
be switched by files with the same name but
without this extension.
To discover which files are these, use the script
link:scripts/my-configuration[] passing the
argument "alternatives" to it:

----
$ ./scripts/my-configuration alternatives
----

So, if you create a file
`./scripts/create-sensitive-tar` it will be used
in place of the file
`./scripts/create-sensitive-tar.sample`.

You can list all alternative files (starting with
`.sample` extension) by running the following
command:

----
$ ./scripts/my-configuration alternative-files
----

Suppose you alternative configuration files
with a suffix '.slim'. To point you configuration
to those files, you can use the following
command:

----
$ ./scripts/my-configuration set slim
----
