vm:
  name: dev-box
  box: paulojeronimo/archlinux
  box_version: 0
  memory: 8192
  disk_size: 80GB
  cpus: 2
# provision:
#   args:
#     - "--use-local-mirror"
  gui: true
  forwarded_ports:
    - guest: 8545 # ganache-cli
      host: 8545
    - guest: 3000 # react
      host: 3000
vbguest_auto_update: false
