vm:
  name: dev-box
  box: finishertech/archlinux-default
  box_version: 0
  memory: 8192
  disk_size: 80GB
  cpus: 2
  provision:
    args:
      - "--use-local-mirror"
  gui: false
  forwarded_ports:
    - guest: 8545 # default port for ganache-cli
      host: 8545
    - guest: 3000 # default port for react apps
      host: 3000
vbguest_auto_update: false
