vm:
  name: dev-box
  box: ubuntu/bionic64
  box_version: 20190911.0.0
  memory: 4096
  disk_size: 80GB
  cpus: 2
  provision:
    script: ubuntu-bionic64
#    args:
#      - "--use-local-mirror"
  forwarded_ports:
    - guest: 8545 # ganache-cli
      host: 8545
    - guest: 3000 # react
      host: 3000
vbguest_auto_update: true
