#!/usr/bin/env bash

apt -y install \
  build-essential \
  gcc \
  g++ \
  make \
  python \
  python-pip \
  jq \
  moreutils

# Installation of Go Language:
add-apt-repository -y ppa:longsleep/golang-backports
apt -y update
apt -y install golang-go
