#!/usr/bin/env bash
DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x

BASE_DIR=`cd "$(dirname "$0")"/..; pwd`
cd "$BASE_DIR"
source ./provision/common/common

if [ $USER = vagrant ]
then
  echo "Creating \"$BACKUP_TAR\" ..."
  mkdir -p "`dirname "$BACKUP_TAR"`"
  create_tar=scripts/create-backup-tar
  [ -f $create_tar ] || create_tar=$create_tar.sample
  bash $create_tar
else
  vagrant ssh -c /vagrant/scripts/backup
fi
