#!/usr/bin/env bash

BASE_DIR=`cd "$(dirname "$0")"/..; pwd`
cd "$BASE_DIR"

backup=tmp/backup.tar.gz
if ! [ -f $backup ]
then
  echo "File $PWD/$backup not found. Aborting!"
  exit 1
fi

read -p "Are you sure (type Y or y to proceed)? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  vagrant destroy -f
  rm -rf .vagrant
fi
