#!/usr/bin/env bash

BASE_DIR=`cd "$(dirname "$0")"/..; pwd`
cd "$BASE_DIR"

read -p "Are you sure (type Y or y to proceed)? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  vagrant destroy -f
  rm -rf .vagrant
fi
