#!/usr/bin/env bash
DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x
set -eo pipefail

BASE_DIR=`cd "$(dirname "$0")"/..; pwd`
cd "$BASE_DIR"
source ./provision/common/common

if [ "$1" != "-f" ] && ! [ -f $BACKUP_TAR ]
then
  echo "File $BACKUP_TAR not found. Aborting!"
  exit 1
fi

read -p "Are you sure (type Y or y to proceed)? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  vagrant destroy -f
  rm -rf .vagrant
fi
