#!/usr/bin/env bash
DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x
set -eou pipefail

export BASE_DIR=`cd "$(dirname "$0")"/..; pwd`
source ./provision/common/common
cd "$BASE_DIR"

remove=false
alternatives=false
alternative_files=false
set_config=false
case "${1:-}" in
  rm) remove=true;;
  alternatives) alternatives=true;;
  alternative-files) alternative_files=true;;
  set) set_config=true;;
esac

function rm_f() { rm "$1"; echo " removed!"; }

function listed() {
  local f
  # https://superuser.com/a/284226
  while IFS= read -r f
  do
    if [ "$1" = "$f" ]; then return 0; fi
  done <<< ${list:-}
  return 1
}

# https://unix.stackexchange.com/a/20039/292211
function push_to_list() { printf -v list "$1\n${list:-}"; echo; }

function echo_file() {
  ! [ -L "$1" ] && echo -n "$1" || {
    echo -n "$1 -> `readlink $1`"
  }
}

if $set_config; then
  name=${2:-}
  [ "$name" ] || { echo "set configuration to what?"; exit 1; }
  for f in $(find . -type f -name "*.sample.$name")
  do
    f_sample=${f%%.sample.$name}
    (
      cd "`dirname "$f"`";
      echo "Linking ${f##*/} to ${f_sample##*/} in ${PWD#$BASE_DIR/}"
      ln -sf ${f##*/} ${f_sample##*/}
    )
  done
  exit 0
fi

if $alternatives; then
  find . -type f -path './config/*'
else
  f=./config.yaml
  ! [ -f "$f" ] || {
    echo_file "$f"
    ! $remove && echo || rm_f "$f"
  }
fi

for f in $(
  find . -type f ! \( -path './.git*' -o -path './tmp*' \) -name '*.sample*' | sort)
do
  if $alternatives
  then
    if ! [ "${f##*.}" = "sample" ]; then continue; fi
    echo $f
    continue
  fi
  if $alternative_files
  then
    if [ "${f##*.}" = "sample" ]; then continue; fi
    echo $f
    continue
  fi
  f_config=${f%*.sample*}
  [ -f "$f_config" ] && {
    if listed "$f_config"; then continue; fi
    echo_file "$f_config"
    ! $remove && push_to_list "$f_config" || rm_f "$f_config"
  }
done
