#!/usr/bin/env bash
DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x
set -eo pipefail

export BASE_DIR=`cd "$(dirname "$0")"/..; pwd`
source ./provision/common/common
cd "$BASE_DIR"

f=./config.yaml
! [ -f "$f" ] || echo "$f"

for f in $(find . -type f ! -path './.git*' -name '*.sample' | sort)
do
  d=`dirname "$f"`
  f_config=$d/`basename "$f" .sample`
  [ -f "$f_config" ] && echo "$f_config"
done
