#!/usr/bin/env bash

# glibc and chromium are requirements to install decktape

pacman --noconfirm -S \
  gcc \
  glibc \
  make \
  python2 \
  python-pip \
  chromium \
  asciidoctor \
  jq \
  go \
  moreutils
