#!/usr/bin/env bash
THIS_DIR=`cd "$(dirname "${BASH_SOURCE[0]}")"; pwd`

config=$THIS_DIR/config
if ! source "$config" &> /dev/null
then
  if [ -f "$config" ]
  then
    echo "Please, verify if there are errors in \"$config\" file!"
    exit 1
  fi
  config=$config.sample
  if ! source "$config" &> /dev/null
  then
    echo "File \"$config\" was not found or contain errors!"
    exit 1
  fi
fi

nvm_dir() {
  local d=/dev/null
  if [ -d ~/.nvm ]
  then
    d=~/.nvm
  elif [ -d ~/.config/nvm ]
  then
    d=~/.config/nvm
  fi
  echo -n $d
}
