#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

pup_repo=github.com/ericchiang/pup
echo "Installing pup ($pup_repo) ..."
go get $pup_repo
