#!/usr/bin/env bash
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"
source ./common

[ -d "$PROJECTS_DIR"/$REACT_SAMPLE_PROJECT ] && ./uninstall-truffle-react-sample || true

echo "Installing $TRUFFLE_REACT_SAMPLE_PROJECT project ..."
mkdir -p "$PROJECTS_DIR"/$TRUFFLE_REACT_SAMPLE_PROJECT && cd "$_"
truffle unbox react 
