#!/usr/bin/env bash
#
# * References:
# ** https://github.com/nvm-sh/nvm#install--update-script
#
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

! [ -d ~/.nvm ] || ./uninstall-nodejs
unset NVM_DIR

echo "Installing nvm ($NVM_VERSION) ..."
curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash

echo "Installing Node.js ($NODEJS_VERSION) via nvm ..."
export NVM_DIR="$HOME/.nvm"   
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install $NODEJS_VERSION

echo "Node.js version is $(node -v)"

echo "Do this command manually: \"source ~/.bashrc\""
