#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

! [ -d "$PROJECTS_DIR/$DOTFILES_PROJECT" ] || ./uninstall-dotfiles

echo "Installing $DOTFILES_PROJECT project ..."
mkdir -p "$PROJECTS_DIR"/${DOTFILES_PROJECT%/*} && cd "$_"
git clone https://$DOTFILES_PROJECT
$(basename $DOTFILES_PROJECT)/install
