#!/usr/bin/env bash
#
# * References:
# ** https://yarnpkg.com/en/docs/install#mac-stable
#
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

[ -d ~/.yarn ] && ./uninstall-yarn || true

echo "Installing yarn ..."
curl -s -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH

echo "Yarn version is $(yarn -v)"

echo "Do this command manually: \"source ~/.bashrc\""
