#!/usr/bin/env bash
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"
source ./common

echo "Installing ganache-cli ($GANACHE_CLI_VERSION) ..."
yarn global add ganache-cli@$GANACHE_CLI_VERSION

echo "Installing truffle ($TRUFFLE_VERSION) ..."
yarn global add truffle@$TRUFFLE_VERSION

echo "Configuring $GANACHE_CLI_BASHRC_CONFIG ..."
cat >> ~/.bashrc <<EOF
# $GANACHE_CLI_BASHRC_CONFIG
export gc_host=10.0.2.15
EOF
