#!/usr/bin/env bash
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"
source ./common

./install-dotfiles
#./install-asciidoctor-gems
#./install-nodejs
#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

#./install-yarn
#export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH

#./install-react-sample
#./install-truffle-suite
#./install-truffle-react-sample
#./install-decktape
./restore-backup
