#!/usr/bin/env bash
#
# * References:
# ** https://github.com/nvm-sh/nvm#install--update-script
#
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"
source ./common

[ -d ~/.nvm ] && ./uninstall-nodejs || true
unset NVM_DIR

echo "Installing nvm ($NVM_VERSION) ..."
curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash

echo "Installing Node.js ($NODEJS_VERSION) via nvm ..."
export NVM_DIR="$HOME/.nvm"   
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install $NODEJS_VERSION

echo "Node.js version is $(node -v)"

echo "Do this command manually: \"source ~/.bashrc\""
