#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

if [ -f "$SENSITIVE_TAR" ]
then
  echo "Extrating \"$SENSITIVE_TAR\" to $HOME ..."
  tar xf "$SENSITIVE_TAR" -C ~
fi
