#!/usr/bin/env bash
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"
source ./common

if [ -f "$BACKUP_TAR_GZ" ]
then
  echo "Restoring \"$BACKUP_TAR_GZ\" ..."
  tar xvfz "$BACKUP_TAR_GZ" -C ~/
fi
