#!/usr/bin/env bash
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"
source ./common

if [ -f "$BACKUP_TAR" ]
then
  echo "Restoring backup (from \"$BACKUP_TAR\") ..."
  tar xf "$BACKUP_TAR" -C ~/
fi
