#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

echo "Uninstalling Node.js ..."
rm -rf ~/.nvm ~/.npm ~/.npmrc
sed -i "/^export NVM_DIR/,+3d" ~/.bashrc
