#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

echo "Uninstalling $DOTFILES_PROJECT ..."
cd $PROJECTS_DIR > /dev/null
$DOTFILES_PROJECT/remove || true
rm -rf $DOTFILES_PROJECT
