#!/usr/bin/env bash
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

echo "Uninstalling $TRUFFLE_REACT_SAMPLE_PROJECT ..."
cd "$PROJECTS_DIR"
rm -rf $TRUFFLE_REACT_SAMPLE_PROJECT
