#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

echo "Uninstalling Yarn ..."
rm -rf ~/.yarn ~/.yarnrc
sed -i "/^export PATH.*yarn/,+1d" ~/.bashrc
