#!/usr/bin/env bash
set -eou pipefail
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

echo "Uninstalling truffle suite ..."
echo "TODO: Complete this script!"

echo "Removing Ganache configuration from ~/.bashrc ..."
sed -i "/^# $GANACHE_CLI_BASHRC_CONFIG$/,+2d" ~/.bashrc
